//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projects_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_feedback
    {
        public int id { get; set; }
        public Nullable<int> evaluator_id { get; set; }
        public Nullable<int> evaluated_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string reason { get; set; }
    
        public virtual pm_User pm_User { get; set; }
        public virtual pm_User pm_User1 { get; set; }
    }
}
